image: docker:latest

build:
 services:
   - docker:dind
 variables:
   DOCKER_HOST: tcp://docker:2375
   DOCKER_DRIVER: overlay2
 script:
   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
   - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
